---
swagger: "2.0"
info:
  description: More description about the API
  version: 1.0.0
  title: Swagger API Doc
host: virtserver.swaggerhub.com
basePath: /Betzy-Salas3/Users/1.0.0
tags:
- name: security-controller
  description: Security Controller
schemes:
- https
paths:
  /login:
    post:
      tags:
      - security-controller
      summary: createToken
      operationId: createTokenUsingPOST
      consumes:
      - application/json
      produces:
      - '*/*'
      parameters:
      - in: body
        name: user
        description: user
        required: true
        schema:
          $ref: '#/definitions/User'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Token'
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      deprecated: false
  /validate:
    get:
      tags:
      - security-controller
      summary: validateToken
      operationId: validateTokenUsingGET
      produces:
      - '*/*'
      parameters:
      - in: body
        name: token
        description: token
        required: true
        schema:
          $ref: '#/definitions/Token'
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      deprecated: false
definitions:
  Token:
    type: object
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/User'
    title: Token
  User:
    type: object
    properties:
      password:
        type: string
      username:
        type: string
    title: User
